unique_ids:
  assets:
    standard-page.html: IBTRKCYXF4HMGWQOZSLUQBPBVQY4KZ2M
    theme.css: AYUUYVYJJCXUWBGUKC7Z2QLF7MA5JZXK
  forms:
    Form1: OVAPTTYJN4UCBLEJACYJET6GXVOYRRCG
  modules: {}
  scripts: {}
  server_modules: {}
